/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exception11;

/**
 *
 * @author anda
 */
public class Exception11 {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here
        x();
    }

    static void x() {
        try {
            y();
        } catch (IllegalStateException e) {
            System.out.println("IllegalStateException in x():  " + e.getMessage());
        } catch (Exception e) {
            System.out.println("Exception in x(): " + e.getMessage());
        }
    }

    static void y() {
        try {
            System.out.println("Before call to z()");
            z();
            System.out.println("After call to z()");
        } catch (NullPointerException e) {
            System.out.println("NullPointerException in y(): " + e.getMessage());
        }
    }

    static void z() {
        throw new IllegalStateException("Exception generated by z() method");
    }

}
